### ISSUE TITLE
Better Indication when Android Time is off

### ISSUE THREAD

**Issue by haraldrudell** [uport-project/uport-android#3]
Android time synchronization is a bit lacking still in 8+

SYMPTOM
This causes the uPort Android client 10000338 to issue **problem syncing 401 - Invalid token** in ☰ - Advanced - System Messages and basically nothing network-related works

CAUSE
However, if one tries to login using qrcode here: https://appmanager.uport.me/
It says: JWT not valid yet (issued in the future): iat: 1530732693 > now: 1530732563.449
revealing what the problem is. My device time was 2 minutes ahead of true time

FIX
One could add an ntp client that would tell you how bad your clock is, or have a better error message

**Comment by mirceanis** [comment]
Issue moved to [uport-project/uport-mobile-issues #28](https://github.com/uport-project/uport-mobile-issues/issues/28) via [**ZenHub**](https://www.zenhub.com/)
